
import {
  Plus,
  Banknote,
  Package,
  CircleDollarSign,
  LayoutDashboard,
  Users,
  Truck,
  ClipboardList,
  Box,
  Factory,
  Scale,
  BarChart3,
  Siren,
  CheckSquare,
  Cylinder,
  ClipboardCheck,
  Palette,
  Warehouse
} from 'lucide-react';
import { DashboardItem } from './types';

export const DASHBOARD_ITEMS: DashboardItem[] = [
  {
    id: 'nova-os',
    label: 'O.S',
    icon: ClipboardList,
    color: 'text-purple-600',
    bgColor: 'bg-purple-100',
  },
  {
    id: 'clientes',
    label: 'Clientes',
    icon: Users,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
  },
  {
    id: 'fechar-caixa',
    label: 'Fechar Caixa',
    icon: Banknote,
    color: 'text-green-600',
    bgColor: 'bg-green-100',
  },
  {
    id: 'contagem',
    label: 'Contagem',
    icon: ClipboardCheck,
    color: 'text-teal-600',
    bgColor: 'bg-teal-100',
  },
  {
    id: 'financeiro',
    label: 'Financeiro',
    icon: CircleDollarSign,
    color: 'text-yellow-600',
    bgColor: 'bg-yellow-100',
  },
  {
    id: 'temas',
    label: 'Temas',
    icon: Palette,
    color: 'text-pink-600',
    bgColor: 'bg-pink-100',
  },
  {
    id: 'painel',
    label: 'Painel',
    icon: LayoutDashboard,
    color: 'text-gray-600',
    bgColor: 'bg-gray-100',
  },
  {
    id: 'estoque',
    label: 'Depósitos & Estoque',
    icon: Warehouse,
    color: 'text-purple-600',
    bgColor: 'bg-purple-100',
  },
  {
    id: 'colaboradores',
    label: 'Colaboradores',
    icon: Users,
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-100',
  },
  {
    id: 'rel-entregas',
    label: 'Rel. Entregas',
    icon: Truck,
    color: 'text-orange-500',
    bgColor: 'bg-orange-100',
  },
  {
    id: 'auditoria',
    label: 'Auditoria',
    icon: ClipboardList,
    color: 'text-orange-400',
    bgColor: 'bg-orange-50',
  },
  {
    id: 'resumo',
    label: 'Resumo',
    icon: BarChart3,
    color: 'text-blue-500',
    bgColor: 'bg-blue-100',
  },
  {
    id: 'alertas',
    label: 'Alertas',
    icon: Siren,
    color: 'text-red-500',
    bgColor: 'bg-red-100',
  },
];
